### ISSUE TITLE
Which JSON-LD profiles are supported?

### ISSUE THREAD

**Issue by wouterbeek** [rubensworks/jsonld-streaming-serializer.js#26]
- Which JSON-LD profiles are currently supported by this implementation?
- And which profiles are intended to be supported?

According to the readme file, compaction (http://www.w3.org/ns/json-ld#compacted) is already supported.  But what about the following formats:
- Expansion (http://www.w3.org/ns/json-ld#expanded)
- Flattening (http://www.w3.org/ns/json-ld#flattened)
- Framing (http://www.w3.org/ns/json-ld#framed)

**Comment by rubensworks** [comment]
This library currently does not support any of these profiles (and there are no plans to support them), as it will just emit triples in JSON-LD as soon as possible.
The profiles above would not always guarantee streamability, which is why this library might not be suitable for these.

There may however be specific profiles (such as specific JSON-LD frames) that _would_ be better suitable for serialization in a streaming manner. While frame-specific serializers would definitely be possible, a generic serializer that can work with any frame could become very complex. (this is an interesting research topic that we've been wanting to look into)

**Comment by wouterbeek** [comment]
Thanks @rubensworks , I understand the scope of the library given its key streaming feature.

Maybe good for future standardization in the area of the Streaming Profile to also address the streaming criteria, if any, for the algorithms/profiles.

**Comment by rubensworks** [comment]
Yes, I agree. I've raised an issue for it here: https://github.com/w3c/json-ld-streaming/issues/29
